# Generated by Django 5.1.2 on 2024-10-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.IntegerField()),
                ('servicePlace', models.TextField()),
                ('comments', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
